/*
 * ULTRASONIC.h
 *
 *  Created on: Oct 14, 2024
 *      Author: nadam
 */
/*****************************************************/
#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"

/*******************Definitions***********************/

#define ULTRASONIC_ECHO_PORT          PORTD_ID
#define ULTRASONIC_ECHO_PIN           PIN6_ID

#define ULTRASONIC_TRIGG_PORT         PORTD_ID
#define ULTRASONIC_TRIGG_PIN          PIN7_ID

#define ULTRASONIC_TRIGG_PULSE        15

/************Functions Prototypes********************/

void Ultrasonic_init(void);                        /* Initialize the ICU driver as required.
                                                    * Set up the ICU callback function.
                                                    * Set the direction for the trigger pin as output through the GPIO driver.  */


void Ultrasonic_Trigger(void);                     /* Send the trigger pulse to the ultrasonic sensor. */


uint16 Ultrasonic_readDistance(void);              /* Send the trigger pulse by using the Ultrasonic_Trigger function.
                                                    * Start the measurement process via the ICU driver. */

void Ultrasonic_edgeProcessing(void);              /* This is the callback function called by the ICU driver.
                                                    * It calculates the high time (pulse time) generated by the ultrasonic sensor. */


#endif /* ULTRASONIC_H_ */
